# Generated by Django 6.0 on 2026-02-02 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_seminars_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminars',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
